train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/merged_dataset/train # training data
      root_path_2: ./load/merged_dataset/GT # ground-truth data
      split_file: ./load/merged_dataset/split.json
      split_key: train
      cache: npy
  wrapper:
    name: moon-paired
    args:
      augment: true
  batch_size: 16

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/merged_dataset/train # validation data
      root_path_2: ./load/merged_dataset/GT # validation ground-truth data
      split_file: ./load/merged_dataset/split.json
      split_key: val
      cache: npy
  wrapper:
    name: moon-paired
    args:
      augment: false
  batch_size: 1

data_norm:
  inp: {sub: [0], div: [1]}  # test ret sub: [0.06], div: [0.12]
  gt: {sub: [0], div: [1]}  # test ret sub: [0.06], div: [0.12]

model:
  name: edsr-moon
  args:
    n_colors: 1

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 500
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 25
